Main svc
i2GR/java-explore-with-me pull request #20
Opened 2023-06-19 23:04 UTC by i2GR

2023-06-21 22:45 UTC, AnastasiyaFomkina requested changes

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-dto/src/main/java/ru/practicum/ewm/app/dto/CategoryDto.java
Лучше объединить оба модуля в один `main-service`, так как эти `dto` используются только внутри `main-server` и отдельно от него они не имеют никакой ценности

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/compilation/publish/CompilationPublicServiceImpl.java
> +    private final EventRepository eventRepo;
Не используется

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/event/admin/EventAdminServiceImpl.java
> +        //categoryIds = categoryIds == null ? List.of() : categoryIds;
Закомментированный код нужно удалить

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/event/admin/EventAdminServiceImpl.java
> +        LocalDateTime persistedEventDate = event.getEventDate();
Код со строк 112-117 повторяется в `EventPrivateServiceImpl` на строках 106-111, нужно избавиться от дублирований

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/event/privitized/EventPrivateController.java
> +        log.info("Private API: get event id {} user id", eventId, userId);
В логе один placeholder `{}`, а аргумента хочешь передавать два

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/event/publish/EventPublicController.java
> +
Лишний отступ

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/partrequest/privatized/PartRequestPrivateServiceImpl.java
> +        for (Long id : ids) {
Нужно заменить на стрим или `forEach()`

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/resources/application.properties
> +#delete
Нужно удалить

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/main/resources/schema.sql
> +    --id BIGSERIAL, -- Postgres
Нужно удалить закомментированный код

2023-06-21 22:45 UTC, AnastasiyaFomkina commented on main-service/main-server/src/test/java/ru/practicum/ewm/app/user/admin/UserAdminControllerTest.java
> +    UserAdminService userAdminService;
Нет модификатора доступа

2023-06-23 12:28 UTC, i2GR commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/partrequest/privatized/PartRequestPrivateServiceImpl.java
> +        for (Long id : ids) {
это как то сложно....
переделал на совсем другое представление

2023-06-23 12:28 UTC, i2GR commented on main-service/main-server/src/main/java/ru/practicum/ewm/app/compilation/publish/CompilationPublicServiceImpl.java
> +    private final EventRepository eventRepo;
удалено. хотя непонятно как так получилось, что оно оставалось.... я класс за классом вычищал все...
все да не все ... не вычистил

2023-06-24 13:38 UTC, AnastasiyaFomkina approved these changes

2023-06-25 11:39 UTC, merged