Stat svc
i2GR/java-explore-with-me pull request #9
Opened 2023-06-05 17:45 UTC by i2GR

2023-06-06 13:49 UTC, AnastasiyaFomkina commented on common/src/main/java/ru/practicum/ewm/common/exception/CommonExceptionHandler.java
> +        return Arrays.stream(throwable.getStackTrace()).map(StackTraceElement::toString).collect(Collectors.toList());
Стрим принято бить по строкам:
```suggestion
        return Arrays.stream(throwable.getStackTrace())
            .map(StackTraceElement::toString)
            .collect(Collectors.toList());
```

2023-06-06 13:57 UTC, AnastasiyaFomkina commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +    public ResponseEntity<Object> postStats(EndpointHitDto dto) {
В `ResponseEntity` лучше оборачивать на уровне контроллера, сервис должен отвечать только за бизнес-логику работы с данными

2023-06-06 13:59 UTC, AnastasiyaFomkina commented on stats-service/stats-server/src/test/java/ru/practicum/ewm/stats/StatsControllerTest.java
> +                .ip("127.0.0.1")
Повторяющийся ip лучше сделать константой

2023-06-06 14:02 UTC, AnastasiyaFomkina requested changes

2023-06-06 14:02 UTC, AnastasiyaFomkina commented on pom.xml
> +	<dependencies>
Блока `<dependencies>` в корневом `pom` быть не должно

2023-06-06 20:55 UTC, i2GR commented on pom.xml
> +	<dependencies>
я не ябедничаю, но у коллег такое встречается;)
подумал, мож мне тоже можно.
но доволен что нельзя таки:))

2023-06-06 20:55 UTC, i2GR commented on stats-service/stats-http-client/src/main/java/ru/practicum/ewm/stats/StatsHttpClientImpl.java
> +import org.springframework.http.*;
спасибо, я помню, спасибо

2023-06-06 20:55 UTC, i2GR commented on common/src/main/java/ru/practicum/ewm/common/exception/CommonExceptionHandler.java
> +        errors.addAll(
спасибо
кажется так (см. пулл-реквест) и без создания ArrayList

2023-06-07 11:43 UTC, AnastasiyaFomkina approved these changes

2023-06-07 11:43 UTC, AnastasiyaFomkina commented on common/src/main/java/ru/practicum/ewm/common/exception/CommonExceptionHandler.java
> +        exception.getBindingResult().getFieldErrors()
👍

2023-06-07 19:22 UTC, merged